apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  name: todo
spec:
  replicas: 1
  selector:
    deployment-config.name: todo
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-config.name: todo
    spec:
      containers:
      - image: todo-api
        name: default-container
        resources: {}
  test: false
  triggers: null
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
